apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  namespace: test-app
spec:
  selector:
    app: test-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
